name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c523131c6e50ac45c78eafee117ccca479639b9f7ba338df72cfe3aa4610bcd8"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
