name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "1.2.0+beta.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3ed961cc820bb6c55c4a468f322eb7ac7f730e99ad85ef3818531bb96f18c6e"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
