name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0414f87a199559ccfc48778e4d24acb55827019362f4ed5b94e7acc0b0be0e9"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
