name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f068d4b8d69135f9e25e54d1c4ebc8542628ffc83339c666db70293ff20046f"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
