name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "1.2.0+beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dfac036cad6bf9f79607cc9c589429a8708f48c2e48d9e2b0e5c64b8951e438"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
