name = "Server Pack 1.19"
author = "MarioAndWeegee3"
version = "1.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "003a4d1dd4df6ca77e935a011d828db00289ebbc6b71e94329fb870c6539ac16"

[versions]
minecraft = "1.19.2"
quilt = "0.17.4"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
